default_platform(:ios)

app_workspace = "./GitRubs.xcworkspace"
app_scheme = "GitRubs"

platform :ios do
  desc "Execute Tests"
  lane :test do
    scan(
      workspace: app_workspace,
      scheme: app_scheme)
    test_coverage()
  end

  desc "Gather test coverage on Slather"
  lane :test_coverage do
    slather(simple_output: true)
  end
end
